---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars:
    build_limit: 2
  vars_prompt:
    - name: "ci_server"
      prompt: "What is the URL of the CI server?"
      default: https://gitlab.com/ci
    - name: "ci_auth_token"
      prompt: "What is your CI auth token?"
      private: yes
  tasks:
    - name: Update apt
      apt: update_cache=yes upgrade=dist

    - name: Install docker
      shell: curl -sSL https://get.docker.com/ | sh

    - name: Install Gitlab repository
      shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | bash

    - name: Install Gitlab CI Multi runner
      apt: name=gitlab-ci-multi-runner state=latest update_cache=yes

    - name: Register the runner
      shell: gitlab-ci-multi-runner register --non-interactive --registration-token={{ ci_auth_token }} --url={{ ci_server }} --executor=docker --limit=2 --docker-image "gitlab/dind:latest"  --docker-privileged
